In [42]:
import torch

In [43]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [44]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [45]:
scalar.ndim
scalar.item()

8

In [46]:
Matrix=torch.tensor([[7, 8],
                     [10, 8]])
Matrix.ndim
Matrix[1]

tensor([10,  8])

In [47]:
TENSOR= torch.tensor([[[1, 2, 3],
                      [3, 5, 4],
                      [5, 8, 9]],
                      [[1, 2, 3],
                       [2, 5, 8],
                       [8, 5, 6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 5, 4],
         [5, 8, 9]],

        [[1, 2, 3],
         [2, 5, 8],
         [8, 5, 6]]])

In [48]:
TENSOR.ndim

3

In [49]:
TENSOR.shape

torch.Size([2, 3, 3])

In [50]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.8662, 0.2054, 0.6069, 0.4139],
        [0.5216, 0.4359, 0.2585, 0.6954],
        [0.1430, 0.4738, 0.7764, 0.7973]])

In [51]:
random_image_size_tensor=torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [52]:
zero=torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
zero.dtype

torch.float32

In [55]:
one_to_ten=torch.range(start=0,end=100,step=20)
one_to_ten

C:\Users\MIT\AppData\Local\Temp\ipykernel_7216\1172636120.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten=torch.range(start=0,end=100,step=20)


tensor([  0.,  20.,  40.,  60.,  80., 100.])

In [56]:
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0.])

## Tensor Datatypes

In [57]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor.dtype

torch.float32

In [58]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [59]:
float_multi=float_16_tensor*float_32_tensor
float_multi

tensor([ 9., 36., 81.])

In [60]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.9139, 0.2623, 0.5123, 0.4164],
        [0.0359, 0.8245, 0.0246, 0.3487],
        [0.6531, 0.6794, 0.2766, 0.0422]])

In [61]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on {some_tensor.device}")

tensor([[0.9139, 0.2623, 0.5123, 0.4164],
        [0.0359, 0.8245, 0.0246, 0.3487],
        [0.6531, 0.6794, 0.2766, 0.0422]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on cpu
