In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Manipulation Tensors
* Addition
* Substraction
* Muiltpliaction
* Division
* Matrix Multiplication

In [2]:
tensor=torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [3]:
tensor * 10

tensor([10, 20, 30])

In [4]:
tensor - 10

tensor([-9, -8, -7])

In [5]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [6]:
print(tensor, '*' , tensor)
print(f"Equal: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [7]:
%%time
torch.matmul(tensor,tensor)

CPU times: total: 0 ns
Wall time: 3.56 ms


tensor(14)

In [8]:
tensor_A=torch.tensor([[8, 2],
                      [3, 4],
                      [5, 6]])

tensor_B=torch.tensor([[3, 3, 4],
                       [1, 5, 7]])


In [9]:
matrix_mul=torch.matmul(tensor_A,tensor_B)
matrix_mul

tensor([[26, 34, 46],
        [13, 29, 40],
        [21, 45, 62]])

In [10]:
matrix_mul.shape

torch.Size([3, 3])

In [11]:
#torch.mean() requries torch.float dtype 
matrix_mul=matrix_mul.type(torch.float)
torch.mean(matrix_mul)

tensor(35.1111)

In [12]:
sample= torch.range(62, 3, -6)
sample

C:\Users\MIT\AppData\Local\Temp\ipykernel_28572\4154668112.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  sample= torch.range(62, 3, -6)


tensor([62., 56., 50., 44., 38., 32., 26., 20., 14.,  8.])

In [13]:
matrix_mul.argmin()

tensor(3)

In [14]:
sample.argmin()

tensor(9)

In [15]:
sample[9]

tensor(8.)

In [16]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [17]:
x_reshaped=x.reshape(1,9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [18]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [19]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [20]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [21]:
print(f"Previous Tensor {x_reshaped}")
print(f"Previous Shape {x_reshaped.shape}")

x_squeezed=x_reshaped.squeeze()
print(f"\nNew Tensor {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous Tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape torch.Size([1, 9])

New Tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [22]:
print(f"Previous Tensor {x_squeezed}")
print(f"Previous Shape {x_squeezed.shape}")

x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous Tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape torch.Size([9])

New Tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [23]:
x_reshaped.squeeze().shape

torch.Size([9])

In [24]:
x_reshaped=x_reshaped.reshape(9,1)
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [25]:
x_orignal=torch.rand(size=(224,224,3))
x_permuted=x_orignal.permute(2,0,1)
print(f"Pervious shape{x_orignal.shape}")
print(f"Pervious shape{x_permuted.shape}")

Pervious shapetorch.Size([224, 224, 3])
Pervious shapetorch.Size([3, 224, 224])


In [26]:
x_orignal[0,0,0]=0.52
x_permuted=x_orignal.permute(2,0,1)
x_permuted[0,0,0]

tensor(0.5200)

In [27]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [28]:
x[:,2,1]

tensor([8])

In [29]:
import numpy as np

array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [30]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy() 
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [31]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C =torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D =torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [32]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [33]:
!nvidia-smi

Wed Oct 29 00:32:10 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.42                 Driver Version: 581.42         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P0             11W /   75W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----