In [1]:
import torch
import numpy as np
from torch import nn

In [2]:
device="cuda"

In [3]:
!nvidia-smi

Wed Dec 10 00:01:59 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   50C    P3             12W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
tensor=torch.tensor([1,2,3],device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [6]:
tensor_back=tensor_on_gpu.cpu().numpy()
tensor_back

array([1, 2, 3])

In [7]:
tensors=torch.randn(7,7,2)
tensors.reshape(2,7,7)

tensor([[[-7.3772e-01,  8.8332e-01, -7.6595e-02, -9.2455e-01, -8.5030e-01,
           1.5566e+00, -3.7895e-01],
         [-3.8919e-01,  1.7071e+00,  1.3473e+00, -1.1036e+00,  1.0340e+00,
          -5.5658e-01, -1.9098e-01],
         [-1.0631e-01, -3.8349e-01, -1.2912e+00, -5.8546e-01,  1.5226e+00,
           5.0707e-01, -9.0249e-01],
         [-2.0027e+00, -1.1585e+00,  7.3210e-01,  8.3179e-01,  1.2701e-01,
          -4.6117e-01, -1.7568e+00],
         [-5.6259e-01, -1.7040e-01,  4.3639e-01, -3.3298e-01, -9.8397e-02,
          -3.3125e+00,  1.7216e-01],
         [ 7.8099e-01, -4.3730e-02,  9.3351e-01, -1.1506e+00,  2.9258e-01,
           2.6563e-01,  3.9384e-01],
         [-7.6383e-01, -2.1635e-01,  6.6435e-01, -9.3793e-01,  1.3377e+00,
           2.2791e+00,  1.8550e+00]],

        [[ 1.8984e+00,  3.7938e-01,  5.9126e-01,  1.1897e+00, -7.8196e-04,
           4.7719e-01, -1.0055e+00],
         [ 1.1255e+00,  1.8243e+00,  5.3717e-01, -1.2622e+00,  3.3931e-01,
           3.1483e-01,  9.3

In [8]:
import numpy as np
array=np.random.randn(2,3,3)
print(array)

[[[ 7.53863356e-01  4.46909064e-01 -2.30933471e-04]
  [-2.58365008e-01 -1.00355848e+00  1.93502805e+00]
  [-5.99346025e-01  3.33869090e-01 -1.24820907e+00]]

 [[-1.71817635e-01 -9.35126166e-01  1.32763034e+00]
  [ 2.84410790e-01 -1.45483592e+00  7.52288210e-01]
  [-1.65534696e-01 -2.35274650e-01  7.90545631e-01]]]


In [9]:
np_tensor=torch.from_numpy(array)
np_tensor.to(torch.float32).dtype
np_tensor.reshape(3,2,3)


tensor([[[ 7.5386e-01,  4.4691e-01, -2.3093e-04],
         [-2.5837e-01, -1.0036e+00,  1.9350e+00]],

        [[-5.9935e-01,  3.3387e-01, -1.2482e+00],
         [-1.7182e-01, -9.3513e-01,  1.3276e+00]],

        [[ 2.8441e-01, -1.4548e+00,  7.5229e-01],
         [-1.6553e-01, -2.3527e-01,  7.9055e-01]]], dtype=torch.float64)

In [10]:
pyt_tensor=np_tensor.numpy()
pyt_tensor.dtype


dtype('float64')

In [11]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A==random_tensor_B)


tensor([[0.2234, 0.5844, 0.9391, 0.7641],
        [0.1430, 0.7913, 0.3177, 0.8095],
        [0.4166, 0.1630, 0.5733, 0.5992]])
tensor([[0.8380, 0.5820, 0.5546, 0.4898],
        [0.3709, 0.6793, 0.4719, 0.5986],
        [0.4777, 0.5851, 0.0422, 0.2259]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [12]:
RANDOM=69
torch.manual_seed(RANDOM)
random_tensor_C=torch.rand(3,3)
torch.manual_seed(RANDOM)
random_tensor_D=torch.rand(3,3)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C==random_tensor_D)

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077],
        [0.0888, 0.2429, 0.7053]])
tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077],
        [0.0888, 0.2429, 0.7053]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [20]:
torch.cuda.is_available()
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [21]:
torch.cuda.device_count()

1

In [30]:
tensor=torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [32]:
tensor_on_gpu=tensor.to("cuda")
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:

tensor_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])